[package]
name = "yatchy-mic-api"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
env_logger = "0.10"
whisper-rs = "0.14.2"
hound = "3.5.0"
fuzzy_match_flex = "0.1.2"
actix-web = "4.0"
tokio = { version = "1.0", features = ["full"] }